name: Deploy Chrome

on:
  workflow_dispatch:

jobs:
  deploy-chrome:
    runs-on: ubuntu-latest
        
    if: startsWith(${{ github.event.head_commit.message }}, 'deploy:')
    steps:
      - name: Download package
        uses: actions/download-artifact@v3
        with:
          path: '/tmp'

      - name: Set zip name
        run: echo "ZIP_NAME=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
      
      - name: Publish to Google Web Store
        run: |
            # Generate a JWT (JSON Web Token)
            WEBSTORE_API_URL="https://www.googleapis.com/chromewebstore/v1.1/${{vars.GOOGLE_APP_ID}}/items"

            echo -e "${{ secrets.GOOGLE_PRIVATE_KEY }}" > /tmp/google-private-key.txt
            cat /tmp/google-private-key.txt
            
            # Generate a JWT (JSON Web Token)
            JWT_HEADER='{"alg":"RS256","typ":"JWT"}'
            JWT_CLAIMS='{"iss":"'"${{ vars.GOOGLE_CLIENT_EMAIL }}"'","scope":"https://www.googleapis.com/auth/chromewebstore","aud":"https://www.googleapis.com/oauth2/v4/token","iat":"'"$(date +%s)"'","exp":"'"$(($(date +%s) + 3600))"'"}'
            BASE64_HEADER=$(echo -n "$JWT_HEADER" | base64 | tr '+/' '-_' | tr -d '=')
            BASE64_CLAIMS=$(echo -n "$JWT_CLAIMS" | base64 | tr '+/' '-_' | tr -d '=')
            SIGNATURE=$(echo -n "$BASE64_HEADER.$BASE64_CLAIMS" | openssl dgst -sha256 -sign /tmp/google-private-key.txt -binary | base64 | tr '+/' '-_' | tr -d '=')
            JWT_TOKEN="$BASE64_HEADER.$BASE64_CLAIMS.$SIGNATURE"

            # Get access token
            ACCESS_TOKEN=$(curl -s -X POST -H "Content-Type: application/json" -d '{"grant_type": "urn:ietf:params:oauth:grant-type:jwt-bearer", "assertion": "'"$JWT_TOKEN"'"}' "https://www.googleapis.com/oauth2/v4/token" | jq -r '.access_token')

            curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T /tmp/artifact/${{ env.ZIP_NAME }}.zip -v "${WEBSTORE_API_URL}"
            curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "${WEBSTORE_API_URL}/publish"
        shell: bash
